### PR TITLE
Add support for PHPUnit 7

### PR DESCRIPTION
**Pull request by keradus**
replaces #23

### CODE REVIEW

**Comment by keradus** [comment]
cc @alister

**Comment by keradus** [comment]
@SpacePossum, @julienfalque, @localheinz - maybe one of you want to take a look ?

**Comment by alister** [comment]
:+1:  on PHP 7.2.1, phpunit 7.0.1, with the dev-phpunit7 branch

**Comment by keradus** [comment]
full matrix is already tested at travis

**Pull request merged**
